<?php

#//\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
#//\\\       \\\\\\\\|
#//\\\ @@    @@\\\\\\| Hot Toddy Calendar View
#//\\ @@@@  @@@@\\\\\|
#//\\\@@@@| @@@@\\\\\|
#//\\\ @@ |\\@@\\\\\\| http://www.hframework.com
#//\\\\  ||   \\\\\\\| © Copyright 2015 Richard York, All rights Reserved
#//\\\\  \\_   \\\\\\|
#//\\\\\        \\\\\| Use and redistribution are subject to the terms of the license.
#//\\\\\  ----  \@@@@| http://www.hframework.com/license
#//@@@@@\       \@@@@|
#//@@@@@@\     \@@@@@|
#//\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
# @description
# <h1>Calendar View</h1>
# <p>
#   This plugin tests the HTML generated by the 
#   <a href='/Hot Toddy/Documentation?hCalendar/hCalendarView/hCalendarView.library.php'>hCalendar/hCalendarView</a> 
#   library.  
# </p>
# <p>
#   It creates a page at: <a href='/Applications/Calendar/view.html' target='_blank' class='code'>/Applications/Calendar/view.html</a>
#   The calendar offset can be adjusted by providing <var>$_GET['calendarOffset']</var> in the 
#   URL.
# </p>
# <p>
#   Style sheets used to generate this calendar view come from:
#   <a href='/System/Framework/Hot Toddy/hCalendar/hCalendarView/hCalendarView.css' target='_blank'>hCalendarView.css</a>, 
#   <a href='/Hot Toddy/Documentation?hCalendar' class='code'>hCalendar</a>, and 
#   <a href='/Hot Toddy/Documentation?hApplication/hApplicationForm' class='code'>hApplication/hApplicationForm</a>
# </p>
# @end

class hCalendarView extends hPlugin {

    private $hCalendarView;

    public function hConstructor()
    {
        # @return void

        # @description
        # <h2>Constructor</h2>
        # <p>
        #   Includes the 
        #   <a href='/Hot Toddy/Documentation?hApplication/hApplicationForm' class='code'>hApplication/hApplicationForm</a>
        #   plugin. Then CSS from: 
        #   <a href='/System/Framework/Hot Toddy/hCalendar/hCalendar.css' target='_blank'>hCalendar.css</a>
        #   then 
        #   <a href='/System/Framework/Hot Toddy/hCalendar/hCalendarView/hCalendarView.css' target='_blank'>hCalendarView.css</a>.
        #   Finally, the HTML from
        #   <a href='/Hot Toddy/Documentation?hCalendar/hCalendarView/hCalendarView.library.php#get'>hCalendarViewLibrary::get()</a> 
        #   is included in the
        #   <a href='/System/Framework/Hot Toddy/hCalendar/hCalendarView/HTML/Solo Calendar.html' target='_blank'>Solo Calendar.html</a>
        #   template.
        # </p>
        # @end
    
        $this->plugin('hApplication/hApplicationForm');
        
        $this->getPluginCSS('hCalendar');
        $this->getPluginCSS();

        $this->hCalendarView = $this->library('hCalendar/hCalendarView');

        $this->hFileDocument = $this->getTemplate(
            'Solo Calendar',
            array(
                'calendar' => $this->hCalendarView->get(null, 'hCalendar', isset($_GET['calendarOffset'])? (int) $_GET['calendarOffset'] : 0)
            )
        );
    }
}

?>