INSERT INTO `hPluginServiceResponseCodes` (
    `hPluginServiceResponseCode`,
    `hPluginServiceResponseText`
) VALUES
(0,   'An unknown error has occurred.'),
(-1,  'You are not authorized to perform the selected operation.'),
(-2,  'A directory or file name may only contain letters, digits or the following characters: _ - . @ '),
(-3,  'A file or directory with that name already exists.'),
(-4,  'The specified operation cannot be performed on a directory.'),
(-5,  'Internal Error, required information missing from request.'),
(-6,  'Login Required. Authentication is required to perform the requested operation.'),
(-7,  'Not authorized. Operation requires elevated privileges.'),
(-8,  'Not authorized. Operation requires root privileges.'),
(-9,  'Not authorized. Operation requires CMS privileges.'),
(-10, 'Operation expects numeric information, however information provided was not numeric.'),
(-11, 'Root account cannot be modified or deleted.'),
(-12, 'Resource is a System File, only the root user may modify System Files.'),
(-13, 'Username already exists.'),
(-14, 'Email already exists.'),
(-15, 'You must be the group liaison to modify group properties.'),
(-16, 'The user you are attempting to contact has blocked chat.'),
(-17, 'A directory cannot be moved to itself.'),
(-18, 'A file cannot be moved to where it already is.'),
(-19, 'Directory does not exist.'),
(-20, 'Destination is not a directory.'),
(-21, 'Directory cannot be moved to a directory that resides within itself.'),
(-22, 'Virtual documents cannot be placed in the server file system.'),
(-23, 'The email address provided is not formatted correctly.'),
(-24, 'The supplied email address is not associated with a valid user account.'),
(-25, 'There is no security question for the specified user account.'),
(-26, 'Login Failed. Invalid username or email address.'),
(-27, 'Login Failed. Invalid password.'),
(-28, 'Login Failed. Account is not activated.'),
(-29, 'Login Failed. The account has been disabled.'),
(-30, 'Login Failed. Too many failed login attempts.'),
(-31, 'Upload Failed. There is a permissions problem with the destination folder.'),
(-32, 'Upload Failed. This file already exists in the file system.'),
(-33, 'File is not writable');
