INSERT INTO `hFrameworkResources` (
    `hFrameworkResourceId`,
    `hFrameworkResourceTable`,
    `hFrameworkResourcePrimaryKey`,
    `hFrameworkResourceNameColumn`,
    `hFrameworkResourceLastModifiedColumn`,
    `hFrameworkResourceLastModifiedByColumn`
) VALUES
    (1,
    'hFiles',
    'hFileId',
    'hFileName',
    'hFileLastModified',
    'hFileLastModifiedBy'),

    (2,
    'hDirectories',
    'hDirectoryId',
    'hDirectoryPath',
    'hDirectoryLastModified',
    'hDirectoryLastModifiedBy'),

    (3,
    'hForums',
    'hForumId',
    'hForum',
    'hForumLastModified',
    'hForumLastModifiedBy'),

    (4,
    'hForumTopics',
    'hForumTopicId',
    'hForumTopic',
    'hForumTopicLastModified',
    'hForumTopicLastModifiedBy'),

    (5,
    'hContacts',
    'hContactId',
    'hContactDisplayName',
    'hContactLastModified',
    'hContactLastModifiedBy'),

    (6,
    'hCalendars',
    'hCalendarId',
    'hCalendarName',
    'hCalendarLastModified',
    'hCalendarLastModifiedBy'),

    (7,
    'hContactAddressBooks',
    'hContactAddressBookId',
    'hContactAddressBookName',
    'hContactAddressBookLastModified',
    'hContactAddressBookLastModifiedBy'),

    (8,
    'hContactAddresses',
    'hContactAddressId',
    'hContactAddressStreet',
    'hContactAddressLastModified',
    'hContactAddressLastModifiedBy'),

    (9,
    'hContactEmailAddresses',
    'hContactEmailAddressId',
    'hContactEmailAddress',
    'hContactEmailAddressLastModified',
    'hContactEmailAddressLastModifiedBy'),

    (10,
    'hContactInternetAccounts',
    'hContactInternetAccountId',
    'hContactInternetAccount',
    'hContactInternetAccountLastModified',
    'hContactInternetAccountLastModifiedBy'),

    (11,
    'hContactPhoneNumbers',
    'hContactPhoneNumberId',
    'hContactPhoneNumber',
    'hContactPhoneNumberLastModified',
    'hContactPhoneNumberLastModifiedBy'),

    (13,
    'hForumPosts',
    'hForumPostId',
    'hForumPostSubject',
    'hForumPostLastModified',
    'hForumPostLastModifiedBy'),

    (14,
    'hFileServer',
    'hFileServerId',
    'hFileServerTitle',
    'hFileServerLastModified',
    'hFileServerLastModifiedBy'),

    (16,
    'hLocationCountries',
    'hLocationCountryId',
    'hLocationCountryName',
    'hLocationCountryLastModified',
    'hLocationCountryLastModifiedBy'),

    (17,
    'hLocationStates',
    'hLocationStateId',
    'hLocationStateName',
    'hLocationStateLastModified',
    'hLocationStateLastModifiedBy'),

    (18,
    'hLocationZipCodes',
    'hLocationZipCode',
    'hLocationZipCode',
    'hLocationZipCodeLastModified',
    'hLocationZipCodeLastModifiedBy'),

    (19,
    'hLocationCounties',
    'hLocationCountyId',
    'hLocationCounty',
    'hLocationCountyLastModified',
    'hLocationCountyLastModifiedBy'),

    (20,
    'hCategories',
    'hCategoryId',
    'hCategoryName',
    'hCategoryLastModified',
    'hCategoryLastModifiedBy'),

    (21,
    'hCalendarFileDates',
    'hCalendarFileDateId',
    'hCalendarDate',
    'hCalendarFileDateLastModified',
    'hCalendarFileDateLastModifiedBy'),

    (22,
    'hCalendarResources',
    'hCalendarResourceId',
    'hCalendarResourceName',
    'hCalendarResourceLastModified',
    'hCalendarResourceLastModifiedBy'),

    (25,
    'hLocationCities',
    'hLocationCityId',
    'hLocationCity',
    'hLocationCityLastModified',
    'hLocationCityLastModifiedBy');